image: node:8.9.4

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - test

test:
  stage: test
  script:
    - npm install -g node-gyp
    - npm install
    - node-gyp rebuild
    - npm test
